# Generated by Django 5.2.7 on 2025-11-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_kassa_kassatransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kassatransaction',
            name='kassa',
        ),
        migrations.RemoveField(
            model_name='kassatransaction',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Kassa',
        ),
        migrations.DeleteModel(
            name='KassaTransaction',
        ),
    ]
